Makefile

As per https://github.com/bwhitman/amy/issues/25
Tested on RPi3.

Add libraries to `Makefile` so AMY compiles on RPi/ARM/32-bit Linux

---

Makefile
README.md
src/AMY-Arduino.cpp
src/AMY-Arduino.h
src/algorithms.c
src/amy-example-rp2040.c
src/amy-example.c
src/amy-message.c
src/amy.c
src/amy.h
src/envelope.c
src/examples.c
src/examples.h
src/oscillators.c

AMY used to have two sets of "event" structures, one for the state of the synth and one for a user/wire parser to indicate what the synth should play. Then we added a third set `i_event`, to allow users to set floating point versions of FXP numbers. This was getting annoying!
This PR significantly cleans this up. Now we've got `synthinfo`, which stores the real time state of each oscillator. And we've got `event`, which is used by end users and our wire protocol parser to indicate to the synth what to do. Those events are turned into `delta`s as they come in, and those `delta`s are played back in real time, updating `synthinfo`. 
This PR also sets all time values to `uint32_t`s, per @dpwe.

Clean up events, synth, delta structures

---

README.md
amy.py
src/amy.c
src/amy.h
src/patches.c

We had an offline imessage design session about this, but basically, this allows anyone using AMY to add patches at runtime by giving `u1024,AMY_PATCH_STRING` where 1024 is a patch number from 1024-1055. This message must be the only thing in the string sent over. `amy.py` will parse it and send it right away, and `amy.c` will treat the rest of the message as a patch, not further messages. 
So you can do:
```
>>> import amy; amy.live()
>>> amy.send(store_patch="1024,v0S0Zv0S1Zv1w0f0.25P0.5a0.5Zv0w0f261.63,1,0,0,0,1A0,1,500,0,0,0L1Z")
>>> amy.send(voices="0",load_patch=1024)
>>> amy.send(voices='0',vel=2,note=50)
```
We divine the number of oscs used for the patch at store_patch time. If you store a new patch over an old one, that old memory is freed and re-allocated. We rely on `malloc` …

Allow patches to be added at runtime

---

README.md
partials.py

Fixes for #140 and #9.
I want @dpwe to look at this first. This apes what `partials.c` does with baked in patches, setting up the EGs in the same way. But to my ears, the default `sleepwalk.mp4` example is "clickier" or more distorted. Luckily, we have an old render to compare against: https://github.com/shorepine/amy/blob/main/sounds/sleepwalk.mp4
To test this, try installing Loris in the new way as indicated in the README update:
```
python3 -m pip install pydub numpy --user
tar xvf loris-1.8.tar
cd loris-1.8
mkdir $HOME/.local # Just in case this doesn't exist
CPPFLAGS=`python3-config --includes` PYTHON=`which python3` ./configure --with-python --prefix=$HOME/.local
make
make install
cd ..
```
And then in `python3`:
```
import partials, amy; amy.live()
(m,s) = …
```

Fixing partials for modern AMY

---

src/envelope.c
src/patches.c

fix for RISCV array bounds checker & tulip osc allocator

---

src/amy.c

Setting `filter_logfreq_coefs[COEF_CONST]` in amy_add_event_internal() is a special case because the specified value is in Hz which must be converted to logfreq units before storing.  However, this special case was implemented twice.  This change removes one of them.

src/amy.c: Remove redundant setting of filter_logfreq_coefs[0]

---

src/amy.c

We hit a problem where setting up an oscillator as an LFO using C led to a zero-amplitude modulator unless you explicitly cleared `amp_coef[COEF_VEL]`, the incorporation of the oscillator note velocity into its overall amplitude, which is set to 1.0 by default. 
However, modulation oscillators never have a nonzero velocity (that would lead to them being audible), so this dependence is unwanted.
With this change, `amp_coef[COEF_VEL]` is automatically cleared for a modulator oscillator when it is set as the `mod_source` for another oscillator.  This increases the undesirable magic side effects of `amy:play_event()`, but I am comfortable with this solution.
If you really wanted the modulating oscillator to depend on velocity, you could rewrite its amp coefficients *after* naming it as the …

src/amy.c: Naming an oscillator as a mod_source clears its amp[VEL].

---

README.md
amy.py
src/amy.c

Several parameters (`freq, amp, filter_freq, duty, pan`) are set via "Control Coefficient" vectors, sets of 7 coefficients that are applied to a fixed set of input signals (`const, note, vel, eg0, eg1, mod, bend`).  These are set via the C API by setting 7-element vectors associated with each parameter, e.g. `event_obj.filter_freq_coefs[COEF_EG1] = 0.5`; when this event is executed, only that one coefficient within the `filter_freq` vector is changed.
Prior to this change, the Python API was different.  Following the wire protocol, changing any coefficient required specifying the entire set, e.g. `amy.send(osc=0, filter_freq='500,0,0,0,1,0,0')`.  For convenience, if fewer than 7 values were specified, the remainder were taken as zero.  Thus, to change a single coefficient, the user had to …

Python API supports setting individual CtrlCoef values

---

src/amy.c
src/amy.h

In #164 we noted that once the noise osc within a Juno voice has hit zero amplitude, subsequent changes to its level will not introduce noise, because the `zero_amp_clock` mechanism has already taken that osc out of `AUDIBLE` status.
This change introduces a new `AUDIBLE_SUSPENDED` status for oscillators that have reached zero amplitude.  Then, if there are later events that modify the amplitude or envelope generator parameters for that osc, and provided it has not seen a note-off since the last note-on, those changes return it from `AUDIBLE_SUSPENDED` to `AUDIBLE`.  If, in fact, those parameter changes still leave the output at zero, the `max_val` check in `render_osc_wave()` will return it to `AUDIBLE_SUSPENDED` within a few frames.

Mechanism to wake up oscs if amplitude changes

---

README.md

..for users wanting to start with patches not oscillators.

README.md: Add a skip-ahead link

---

README.md

This is potentially confusing otherwise.

Clarify the interaction of voices and oscs in README.md

---

README.md
src/amy.c
src/amy.h

This allows updating single values (times or values) of existing BP sets.  However, the total number of values indicated, even if not set, defines the total length of the BP set, so you have to add bare commas for all the trailing values you're not specifying too.

Unspecified values in bp sets (bare commas) do not change existing breakpoint values

---

src/amy.c

Oops.  Printed out the values when setting bp sets.

src/amy.c: Remove debug fprintf included by error.

---

src/pcm.c

Sending a note-off to a PCM voice before it completed by itself had the opposite effect of rewinding it to nearly the beginning, sounding like a retrigger. Turns out I was using the wrong scale-up when trying to fast-forward the position-within-sample pointer to the end, so I was instead rewinding to near the beginning.  After this fix, sending note-offs to active PCM voices does in fact stop them immediately.

Pcm note off

---

src/amy.c

Without this fix, we can't do note offs in the memorypcm custom type

Checking for feedback on CUSTOM (tulip memorypcm type) as well

---

README.md
amy.py
src/amy.c
src/amy.h
test.py

The old hack of using a negative patch number with wave=PARTIALS still works, and indeed BYO_PARTIALS num_partials=... uses the same wire-code letter as patch, and the message decoder simply flips the sign of it for BYO.  Thereafter PARTIALS and BYO_PARTIALS are treated the same. 
TODO: Cleanup the distinction between PARTIALS and BYO_PARTIALS in the code, which is currently mediated by looking for a negative patch value in the individual PARTIAL oscs, even though they don't need or care about patch number for anything else.

Added wave=BYO_PARTIALS for cleaner BYO_PARTIALS syntax.

---

amy.py

I made Amy.send() raise a ValueError if args were passed with value None, but it turns out we do this with time= a lot.

amy.py: Tolerate amy.send(time=None).

---

README.md
src/examples.c

The example that plays a couple of FM tone by directly configuring the individual sine oscillators had been broken since we made the change that unspecified ControlCoefficients are left unchanged (rather than being cleared to zero).  Because FM component oscs do not see the velocity of their parent note, it's important to include `amp={'vel': 0}` (to clear the default weight of 1), otherwise the operator oscs will always have zero output, because they see a velocity of zero.
Doing this, I realize that `ratio` is really just a special case of ControlCoefficients.  Instead of `ratio=0.2` (and the associated explanation), that's really just `freq={'const':  52.326, 'note': 1}`, i.e. it follows the note frequency, but relative to 0.2 x the default frequency (of 261.63 Hz).  We could change …

README.md: Fix the FM example to clear amp[VEL].

---

README.md
amy.py
src/amy.c
src/amy.h
src/examples.c
test.py

For _reasons_ (Amy chip, and amy-web) I would like to be able to send AMY a message to reset its time base to 0, so that future calls with time=x start from 0. 
I _personally_ see this as a form of “reset”. We already have the notion that reset_osc set to > AMY_OSCS (120) resets all of the oscs. 
What I posit to you is what if we had an even bigger reset, like reset_osc = 10000 , that also restarted audio (including the audio clock?)

reset_osc with RESET_TIMEBASE resets time clock

---

README.md
src/CMakeLists.txt

Note that I have not tested the pico `CMakeLists.txt` change, I used those files to make my own `CMakeLists.txt` for my own project (non-pico), and noticed that the code wouldn't compile if I didn't add the `transfer.c` file.

A minor documentation fix, and addition of a missing file in pico's cmakelists

---

Makefile
README.md
amy.py
src/amy.c
src/amy.h
src/patches.c
src/sequencer.c
src/sequencer.h
src/setup.py

This PR adds the sequencer to AMY. We have new `sequence` and `tempo` commands. 
This allows anyone to have a Tulip-style clock sequencer running directly in AMY. 
README.md has the API for it and some examples. 
This gets us closer to fixing up https://github.com/shorepine/tulipcc/issues/340

Sequencer in AMY

---

README.md
src/amy.c

RESET_TIMEBASE was being scheduled, which meant a call like 
```
amy.send(reset=amy.RESET_TIMEBASE)
amy.send(osc=0,freq=440,vel=1,time=0)
amy.send(osc=0,freq=220,vel=1,time=100)
```
Would not actually work properly, as the TIMEBASE was not reset until after the scheduling of the freq messages.
In this PR we reset timebase immediately on parsing. We updated the docs.

fixing RESET_TIMEBASE

---

src/amy.c
src/partials.c

For the forthcoming walkthrough of the additive-synthesis piano, I want to be able to modify the amp_coef[CONST] of PARTIAL oscs without it getting clobbered each note on.  This cleanup seems to be generally sane and mostly safe (as long as the PARTIALs osc are reset before being deployed) so I wanted to put it into the main branch.

partials.c: PARTIALs no longer reset amp_coefs at every note-on.

---

src/amy.c

The sequencer was not getting its ticks set to 0 on RESET_TIMEBASE. This does that.

reset sequencer ticks to 0 (and recompute sequencer) on timebase reset

---

src/amy-example.c
src/amy.c
src/amy.h
src/patches.c
src/sequencer.c

This makes it so the sequencer stores / sequences deltas instead of full events. With full events, it was a big memory user (see #74 )
This also adds a new `callback` arg to the methods that parse events into deltas, so we can choose where to send them. 
Tested on tulip web's sequencer use cases

Sequence deltas, not full `event`s 

---

src/interp_partials.c

@drepetto reported that notes below around A0 on synth patch 256 (dpwe piano) blew up quite unpleasantly.  This is because the lowest note in the harmonics table is C1, so notes below that are being extrapolated from the difference between C1 and Eb1, which apparently led to some extreme growth for some time points of some harmonics.
I avoided the worst of this behavior by clipping the dB magnitudes of the harmonic envelopes to 120 dB (where 0 is the floor).  These super low notes are still weird, but at least they don't drive the output into wrap-around clip.

interp_partials.c: Clip partial magnitudes

---

README.md
src/amy.h
src/instrument.c
src/midi.c
src/patches.c

Previously, MIDI program changes resulted in a `load_patch` in the range 0-127 (the juno patches).  But if you had initialized that instrument to a DX7 patch (`load_patch` 128-255), a program change would change you to a juno.
This change keeps track of the current `patch_number` associated with an instrument, then the MIDI program change only modifies the lowest 7 bits of this value.  Thus, a program change sent to an instrument playing a DX7 patch will select a different DX7 patch.

MIDI program changes remain with the current block of 128.

---

amy.py
src/amy.c
src/patches.c
src/sequencer.c

Make sure amy_millis() doesn't overflow at 1.1 h when promoting to microseconds.
[unrelated] Allows wave=PATCH note-ons to omit note number for synth/instrument note-ons.

sequencer.c: Handle us in 64 bit.

---

README.md
amy.py
src/patches.c
test.py

`e->instrument_flags` was introduced in #329.  This change makes it controllable via the Python API and adds a test.
I used an alias of wire code 'o' (algorithm) on the thought they're unlikely to be used together.

Synth flags

---

src/midi.c

- **moving task names to amy.h for tulip**
- **making midi out not crash on linux**

making midi out not break on linux

---

src/algorithms.c
src/amy-example.c
src/amy.c
src/amy.h
src/envelope.c
src/examples.c
src/filters.c
src/interp_partials.c
src/midi.c
src/oscillators.c
src/partials.c
src/patches.c
src/pcm.c

This avoids the big 150k alloc for all the synthinfos.  Doesn't reduce the peak memory need when trying to use a lot of oscs, but will hide it unless you try to use them all.

synth[] and modsynth[] are dynamically allocated per osc, only when used

---

src/instrument.c
src/parse.c
src/patches.c

xanadu.py needs 35 voices total, 18 of them in a single instrument.

fix reset_osc logic; extend MAX_VOICES and MAX_VOICES_PER_INSTRUMENT.

---

src/midi.c

There wasn't any instance of the buffer overrunning, but by explicitly preventing it, we can run safely with a much smaller buffer.  I tested the buffer of 16 on the Pico, and rapid knob twiddles had no perceptible performance impact.

src/midi.c: Guard against midi buffer overrun on Pico.

---

src/amy.c

Juno 0 was not running VCF on Tulip because osc 0 (pulse, but also VCF) had amp_coefs of essentially zero.

src/amy.c: Make sure oscs with chained_osc dependents are turned on.

---

src/amy-example.c
src/instrument.c
src/midi.c

I imagined that `instrument_number_ok` actually meant `instrument_number_exists`, so started accessing members if it passed.  But `instrument_number_ok` was just checking that it was within range (0..`max_instruments - 1`).  Now I use a new function, `instrument_number_exists`, when that is what I want to confirm.

src/instrument.c: Check that an instrument exists before accessing it

---

examples/AMY_MIDI_Synth/AMY_MIDI_Synth.ino

Some people are surprised that their library starts up with so much specific state.  This at least leaves a little reminder.

AMY_MIDI_Synth.ino: Make features.default_synths=1 explicit.
